// frontend/src/components/Auth.vue
<template>
  <div>
    <p v-if="loggedIn">{{loggedIn}}</p>
    <p v-if="loginRedirect">Login</p>
  </div>
</template>

<script>
import Api from '../service/Api';

const api = new Api();

export default {
  name: 'auth',
  data() {
    return {
      loginRedirect: false,
      loggedIn: false
    }
  }, 
  created() {
    const code = (new URL(window.location)).searchParams.get("code");
    if (code) {
      api
        .setAuthCode(code)
        .then(() => window.location.replace("/"));
    } else {
      api
        .getCurrentUser()
        .then(it => {
          if (it.redirect) {
            this.loginRedirect = it.redirect;
            this.loggedIn = false;
          }
          if (it.displayName) {
            this.loggedIn = it.displayName;
            this.loginRedirect = false;
          }
        });
    }
  }
}
</script>

<style scoped>
</style>

// frontend.react/src/component/auth/Auth.js
import React, { Component } from 'react';
import Api from '../../service/Api';

export default class Auth extends Component {
  api = new Api();

  constructor(props) {
    super(props);
    this.state = {
      loggedIn: false,
      loginRedirect: false
    }
  }

  componentDidMount() {
    const code = (new URL(window.location)).searchParams.get("code");
    if (code) {
      debugger;
      this
        .api
        .setAuthCode(code)
        .then(() => {
          window.location.replace("/");
        });
      return
    }

    this
      .api
      .getCurrentUser()
      .then(it => {
        if (it.redirect) {
          this.setState({
            loginRedirect: it.redirect,
            loggedIn: false
          })
        }
        if (it.displayName) {
          this.setState({
            loggedIn: it.displayName,
            loginRedirect: false
          })
        }
      })
  }


  render() {
    return (
      <div>
        {
          this.state.loggedIn &&
          <p>Welcome { this.state.loggedIn }</p>
        }
        {
          this.state.loginRedirect &&
          <a href={ this.state.loginRedirect }>Login</a>
        }
      </div>
    )
  }
}
