// frontend.react/src/App.js
import React, {Component} from 'react';
import {Tabs, Tab} from "react-bootstrap";
import Header from "./component/header/Header";
import Items from "./component/items/Items";
import "./app.css";
import Music from "./component/music/Music";

export default class App extends Component {
    render() {
        return (
            <div className="App">
                <Header/>
                <div className="content">
                    <Tabs id="tabs" defaultActiveKey="files">
                        <Tab eventKey="files" title="Files">
                            <Items/>
                        </Tab>
                        <Tab eventKey="music" title="Music">
                            <Music/>
                        </Tab>
                    </Tabs>
                </div>
            </div>
        );
    }
}

// frontend/src/App.vue
<template>
  <div class="App">
    <HeaderBar></HeaderBar>
    <div class="content">
      <b-tabs>
        <b-tab title="Files" active>
          <Items/>
        </b-tab>
        <b-tab title="Music">
          <Music/>
        </b-tab>
      </b-tabs>
    </div>
  </div>
</template>

<script>
import HeaderBar from './components/HeaderBar.vue';
import Items from './components/items/Items.vue';
import Music from './components/items/Music.vue';

export default {
  name: 'app',
  components: {
    HeaderBar,
    Items,
    Music
  }
}
</script>

<style scoped>
.content {
  max-width: 1000px;
  margin: auto;
}
.tabs {
  margin-top: 15px;
}
</style>
